{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ include "globalResourceName" (dict "name" "scc" "root" .) }}
runAsUser:
  type: MustRunAsNonRoot
seccompProfiles:
  - '*'
seLinuxContext:
  type: RunAsAny
users:
  {{- if .Values.admissionController.enabled }}
  - system:serviceaccount:{{ include "namespace" . }}:{{ include "admissionController.resourceNamePrefix" . }}-service-account
  {{- end }}
  {{- if .Values.connector.enabled }}
  - system:serviceaccount:{{ include "namespace" . }}:{{ include "connector.resourceNamePrefix" . }}-service-account
  {{- end }}
  - system:serviceaccount:{{ include "namespace" . }}:{{ include "updater.resourceNamePrefix" . }}-service-account
volumes:
  - csi
  - emptyDir
  - secret
{{- end }}