apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "updater.labels" . | nindent 4 }}
  name: {{ include "updater.globalResourceName" (dict "name" "crb" "root" .) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "updater.globalResourceName" (dict "name" "cr" "root" .) }}
subjects:
- kind: ServiceAccount
  name: {{ include "updater.resourceNamePrefix" . }}-service-account
  namespace: {{ include "namespace" . }}
