apiVersion: v2
description: A Helm chart to deploy Tenable Security Center into Kubernetes clusters
type: application
home: https://www.tenable.com
sources:
  - https://github.com/tenable/helm-charts
maintainers:
  - name: Tenable SecurityCenter
    email: securitycenter@tenable.com
name: securitycenter
appVersion: "6.3.0"
version: 1.1.0