apiKeyToken: ""
apiKeyTokenSecretName: ""
apiUrl: ""
containerImagePath: tenable/cloud-security-endpoint-connector
containerImagePullSecrets: []
pod:
  affinity: {}
  annotations: {}
  labels: {}
  resources: {}
  tolerations: []
proxyUrl: ""
serviceEndpoint: ""
serviceId: ""
resourceNamePrefix: endpoint-connector